[package]
name = "connlib-client-android"
# mark:next-android-version
version = "1.4.0"
edition = "2021"

[lib]
name = "connlib"
crate-type = ["lib", "cdylib"]
doc = false

[dependencies]
backoff = "0.4.0"
connlib-client-shared = { workspace = true }
connlib-model = { workspace = true }
firezone-logging = { workspace = true }
firezone-telemetry = { workspace = true }
ip_network = "0.4"
jni = { version = "0.21.1", features = ["invocation"] }
libc = "0.2"
log = "0.4"
phoenix-channel = { workspace = true }
rustls = { workspace = true }
secrecy = { workspace = true }
serde_json = "1"
socket-factory = { workspace = true }
thiserror = "1"
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true, features = ["std", "attributes"] }
tracing-appender = "0.2"
tracing-subscriber = { workspace = true }
tun = { workspace = true }
url = "2.5.2"

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.3.1"

[lints]
workspace = true
