[package]
name = "firezone-tunnel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = { version = "0.22", default-features = false, features = ["std"] }
bimap = "0.6"
boringtun = { workspace = true }
bytes = { version = "1.7", default-features = false, features = ["std"] }
chrono = { workspace = true }
connlib-model = { workspace = true }
derivative = "2.2.0"
divan = { version = "0.1.14", optional = true }
dns-over-tcp = { workspace = true }
domain = { workspace = true }
firezone-logging = { workspace = true }
futures = { version = "0.3", default-features = false, features = ["std", "async-await", "executor"] }
futures-bounded = "0.2.4"
futures-util = { version = "0.3", default-features = false, features = ["std", "async-await", "async-await-macro"] }
glob = "0.3.1"
hex = "0.4.3"
ip-packet = { workspace = true }
ip_network = { version = "0.4", default-features = false }
ip_network_table = { version = "0.2", default-features = false }
itertools = { version = "0.13", default-features = false, features = ["use_std"] }
lru = "0.12.5"
proptest = { version = "1", optional = true }
rand = "0.8.5"
rangemap = "1.5.1"
secrecy = { workspace = true, features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = "1.0"
snownet = { workspace = true }
socket-factory = { workspace = true }
socket2 = { workspace = true }
thiserror = { version = "1.0", default-features = false }
tokio = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
tun = { workspace = true }
uuid = { version = "1.10", default-features = false, features = ["std", "v4"] }

[dev-dependencies]
derivative = "2.2.0"
firezone-relay = { workspace = true, features = ["proptest"] }
ip-packet = { workspace = true, features = ["proptest"] }
proptest-state-machine = "0.3"
rand = "0.8"
sha2 = "0.10.8"
test-case = "3.3.1"
test-strategy = "0.3.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bench]]
name = "divan"
harness = false
required-features = ["divan"]

[features]
proptest = ["dep:proptest"]
divan = ["dep:divan"]

[lints]
workspace = true
