[package]
name = "firezone-gui-client"
# mark:next-gui-version
version = "1.3.13"
description = "Firezone"
edition = "2021"
default-run = "firezone-gui-client"
authors = ["Firezone, Inc."]

[build-dependencies]
anyhow = { version = "1.0.89" }
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
anyhow = { version = "1.0.89" }
atomicwrites = { workspace = true }
chrono = { workspace = true }
clap = { version = "4.5.20", features = ["derive", "env"] }
connlib-client-shared = { workspace = true }
connlib-model = { workspace = true }
firezone-bin-shared = { workspace = true }
firezone-gui-client-common = { path = "../src-common" }
firezone-headless-client = { path = "../../headless-client" }
firezone-logging = { workspace = true }
firezone-telemetry = { workspace = true }
native-dialog = "0.7.0"
rand = "0.8.5"
rustls = { workspace = true }
sadness-generator = "0.6.0"
secrecy = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
subtle = "2.5.0"
tauri = { version = "2.0.3", features = ["tray-icon", "image-png"] }
tauri-plugin-dialog = "2.0.1"
tauri-plugin-notification = "2.0.1"
tauri-plugin-shell = "2.0.2"
tauri-runtime = "2.1.0"
tauri-utils = "2.0.1"
thiserror = { version = "1.0.68", default-features = false }
tokio = { workspace = true, features = ["signal", "time", "macros", "rt", "rt-multi-thread"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = { version = "2.5.2", features = ["serde"] }
uuid = { version = "1.10.0", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dependencies]
dirs = "5.0.1"
nix = { version = "0.29.0", features = ["user"] }

[target.'cfg(target_os = "macos")'.dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
tauri-winrt-notification = "0.7.0"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58.0"
features = [
  "Win32_Foundation",
  "Win32_System_Threading",
]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
# TODO: We can probably remove this, per <https://github.com/tauri-apps/tauri/releases/tag/tauri-v2.0.0-beta.8>
# I don't know how to verify this change, so I won't do it right now.
custom-protocol = ["tauri/custom-protocol"]

[lints]
workspace = true
