[workspace]
members = [
  "bin-shared",
  "connlib/clients/android",
  "connlib/clients/apple",
  "connlib/clients/shared",
  "connlib/model",
  "connlib/snownet",
  "connlib/tunnel",
  "dns-over-tcp",
  "gateway",
  "gui-client/src-common",
  "gui-client/src-tauri",
  "headless-client",
  "ip-packet",
  "logging",
  "phoenix-channel",
  "relay",
  "socket-factory",
  "telemetry",
  "tests/gui-smoke-test",
  "tests/http-test-server",
  "tun",
]

resolver = "2"

[workspace.dependencies]
atomicwrites = "0.4.4"
boringtun = { version = "0.6", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
swift-bridge = "0.1.57"
backoff = { version = "0.4", features = ["tokio"] }
tracing = { version = "0.1.40" }
tracing-macros = { git = "https://github.com/tokio-rs/tracing", branch = "v0.1.x" } # Contains `dbg!` but for `tracing`.
tracing-subscriber = { version = "0.3.17", features = ["parking_lot"] }
secrecy = "0.8"
str0m = { version = "0.6.2", default-features = false }
futures-bounded = "0.2.1"
domain = { version = "0.10", features = ["serde"] }
dns-lookup = "2.0"
tokio-tungstenite = "0.23.1"
rtnetlink = { version = "0.14.1", default-features = false, features = ["tokio_socket"] }
tokio = "1.41"
rustls = { version = "0.23.10", default-features = false, features = ["ring"] }

connlib-client-android = { path = "connlib/clients/android" }
connlib-client-apple = { path = "connlib/clients/apple" }
connlib-client-shared = { path = "connlib/clients/shared" }
firezone-bin-shared = { path = "bin-shared" }
firezone-logging = { path = "logging" }
firezone-telemetry = { path = "telemetry" }
snownet = { path = "connlib/snownet" }
dns-over-tcp = { path = "dns-over-tcp" }
firezone-relay = { path = "relay" }
connlib-model = { path = "connlib/model" }
firezone-tunnel = { path = "connlib/tunnel" }
phoenix-channel = { path = "phoenix-channel" }
ip-packet = { path = "ip-packet" }
socket-factory = { path = "socket-factory" }
tun = { path = "tun" }
socket2 = { version = "0.5" }

[workspace.lints.clippy]
dbg_macro = "warn"
print_stdout = "warn"
print_stderr = "warn"
unnecessary_wraps = "warn"
unused_async = "warn"
wildcard_enum_match_arm = "warn" # Ensures we match on all combinations of `Poll`, preventing erroneous suspensions.
redundant_else = "warn"
redundant_clone = "warn"
unwrap_in_result = "warn"
unwrap_used = "warn"

[workspace.lints.rustdoc]
private-intra-doc-links = "allow" # We don't publish any of our docs but want to catch dead links.

[patch.crates-io]
smoltcp = { git = "https://github.com/smoltcp-rs/smoltcp", branch = "main" }
quinn-udp = { git = "https://github.com/quinn-rs/quinn", branch = "main" }
boringtun = { git = "https://github.com/firezone/boringtun", branch = "master" }
str0m = { git = "https://github.com/algesten/str0m", branch = "main" }
ip_network = { git = "https://github.com/JakubOnderka/ip_network", branch = "master" } # Waiting for release.
ip_network_table = { git = "https://github.com/edmonds/ip_network_table", branch = "some-useful-traits" } # For `Debug` and `Clone`
proptest = { git = "https://github.com/proptest-rs/proptest", branch = "main" }
proptest-state-machine = { git = "https://github.com/proptest-rs/proptest", branch = "main" }
tracing-stackdriver = { git = "https://github.com/thomaseizinger/tracing-stackdriver", branch = "bump-otel-0.26" } # Waiting for release.

# Enforce `tracing-macros` to have released `tracing` version.
[patch.'https://github.com/tokio-rs/tracing']
tracing = "0.1.40"

[profile.release]
strip = true

# Full link-time optimization. Reduces binaries by up to 3x on some platforms.
lto = "fat"

# Increases the compiler's ability to produce smaller, optimized code
# at the expense of compilation time
codegen-units = 1

[profile.bench]
strip = false # Frame pointers are necessary for profiling; `strip=true` appears to remove them.

# Override build settings just for the GUI client, so we get a pdb/dwp
# Cargo ignores profile settings if they're not in the workspace's Cargo.toml
[profile.dev.package.firezone-gui-client]
debug = "full"
split-debuginfo = "packed"
strip = "none"

[profile.release.package.firezone-gui-client]
debug = "full"
split-debuginfo = "packed"
strip = "none"
