[package]
name = "socket-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
firezone-logging = { workspace = true }
quinn-udp = { version = "0.5.7", features = ["fast-apple-datapath"] }
socket2 = { workspace = true }
tokio = { version = "1.41", features = ["net"] }
tracing = "0.1"
